apiVersion: v2
appVersion: 1.7.0
dependencies:
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.78.0
- condition: jaeger.enabled
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 0.73.1
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.8.2
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.2.1
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
- name: dmitryax
- name: puckpuck
- name: tylerhelmuth
name: opentelemetry-demo
sources:
- https://github.com/open-telemetry/opentelemetry-demo
type: application
version: 0.28.1
