
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
- name: opentelemetry-demo
  # repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.28.1
  releaseName: otel-demo
  namespace: otel-demo
  valuesFile: values.yml


resources:
- namespace.yml
