# # components:
# #   frontend:
# #     env:
# #       - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
# #         value: http://localhost:30080/otlp-http/v1/traces

# default:
#   # List of environment variables applied to all components
#   env:
#     - name: OTEL_SERVICE_NAME
#       valueFrom:
#         fieldRef:
#           apiVersion: v1
#           fieldPath: "metadata.labels['app.kubernetes.io/component']"
#     - name: OTEL_COLLECTOR_NAME
#       value: '{{ include "otel-demo.name" . }}-otelcol'
#     - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
#       value: cumulative
#     - name: OTEL_RESOURCE_ATTRIBUTES
#       value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo